version: "3.9"

name: discord-bot
services:
  bot:
    build: .
    volumes:
      - ./app:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    entrypoint: ["/bin/sh", "-c"]
    command:
      - python main.py
